stages:
  - build
  - test
  - deploy

variables:
  DeploymentFileName: buildFiles


build:
  stage: build
  tags:
    - ugrad
  script:
    - mvn clean compile


test:
  stage: test
  tags:
    - ugrad
  script:
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failfire-reports/TEST-*.xml

deploy:
  stage: deploy
  tags:
    - ugrad
  only:
    - develop
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
  script:
    echo "Start Deployment"
    - chmod og-rwx ${DEPLOY_SSH_KEY}
    - zip -r ${DeploymentFileName}.zip target
    - scp -r -i "${DEPLOY_SSH_KEY}" -o StrictHostKeyChecking=no ${DeploymentFileName}.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${DeploymentFileName}.zip"


#    - scp -r -o StrictHostKeyChecking=no -i "${DEPLOY_SSH_KEY}" ${EXECUTABLE_TO_DEPLOY} "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${DESTINATION_FILE}"
