stages:
  - build
  - test
  - deploy

variables:
  DeploymentFileName: buildFiles

build:
  stage: build
  tags:
    - ugrad
  except:
    - release
    - master
  script:
    - mvn clean compile
    - mvn package
  artifacts:
    when: on_success
    paths:
      - target/*.jar

release_build:
  stage: build
  tags:
    - ugrad
  only:
    - release
  script:
    - mvn clean compile
    - mvn package -P test
  artifacts:
    when: on_success
    paths:
      - target/*.jar

master_build:
  stage: build
  tags:
    - ugrad
  only:
    - master
  script:
    - mvn clean compile
    - mvn package -P prod
  artifacts:
    when: on_success
    paths:
      - target/*.jar

test:
  stage: test
  tags:
    - ugrad
  script:
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failfire-reports/TEST-*.xml

DevelopDeploy:
  stage: deploy
  tags:
    - ugrad
  only:
    - Develop
  before_script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
  script:
    - echo "Start Connecting"
    - echo "$DEPLOY_SSH_KEY" >> ~/.ssh/gitlab-ci-delivery
    - chmod og-rwx ~/.ssh/gitlab-ci-delivery
    - scp -r -o StrictHostKeyChecking=no "target/BankApp.jar" "${DEPLOY_USER}@${DEPLOY_HOST}:${DEV_DEPLOY_DIR}"

ProductionDeploy:
  stage: deploy
  tags:
    - ugrad
  only:
    - master
  before_script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
  script:
    - echo "Start Connecting"
    - echo "$DEPLOY_SSH_KEY" >> ~/.ssh/gitlab-ci-delivery
    - chmod og-rwx ~/.ssh/gitlab-ci-delivery
    - scp -r -o StrictHostKeyChecking=no "target/BankApp.jar" "${DEPLOY_USER}@${DEPLOY_HOST}:${MASTER_DEPLOY_DIR}"

TestDeploy:
  stage: deploy
  tags:
    - ugrad
  only:
    - release
  before_script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
  script:
    - echo "Start Connecting"
    - echo "$DEPLOY_SSH_KEY" >> ~/.ssh/gitlab-ci-delivery
    - chmod og-rwx ~/.ssh/gitlab-ci-delivery
    - scp -r -o StrictHostKeyChecking=no "target/BankApp.jar" "${DEPLOY_USER}@${DEPLOY_HOST}:${RELEASE_DEPLOY_DIR}"
